#
#  _                                                      _
# (_)_ ____   __    _ __   __ _  __ _  ___  ___     _ __ | |_   _ ___
# | | '_ \ \ / /   | '_ \ / _` |/ _` |/ _ \/ __|   | '_ \| | | | / __|
# | | | | \ V /    | |_) | (_| | (_| |  __/\__ \   | |_) | | |_| \__ \
# |_|_| |_|\_(_)   | .__/ \__,_|\__, |\___||___/   | .__/|_|\__,_|___/
#                  |_|          |___/              |_|
# A plugin made by Cortez_Romeo
#
# Contact me:
# discord account: Cortez_Romeo
# discord server: https://discord.gg/NWbTVddmBM
#
# Please join my discord server to report bugs, giving suggestions. Thank you for supporting plugin!

# Use to show plugin information in order to support me fixing bugs.
# You might be asked to turn this on if you have plugin troubles. Otherwise, you don't have to turn this on.
debug:
  enabled: false
  prefix: '&e[INV.PAGES+ DEBUG] '

# What based database will be used for storing player's inventory.
database:
  # H2, MYSQL, YAML
  # Loading database on H2/MYSQL is faster than YAML, so I recommend using H2/MYSQL.
  # For multiple server setups, use MYSQL.
  # For single server setup, use H2.
  type: H2
  settings:
    h2:
      file-name: 'h2Database'
      table: 'inventorydata'
    mysql:
      database:
        host: localhost
        port: 3306
        name: inventorypagesplus
        table: inventorydata
        user: root
        password: ''

# Set the locale for all messages.
# To set language to English, set locale to en, to use the file "messages_en.yml" in folder "languages".
# You can create your own message file by following these steps:
#         1. copy messages_en.yml
#         2. paste it to folder languages with a new file name
#         3. file name must be: messages_<your locale>.yml
#         4. After you're done editing your message file, go back to config.yml and change "locale" to <your locale>
# Default languages available: en, vi
locale: en

auto-save:
  enabled: true
  # Auto save database each...
  seconds: 900

backup-settings:
  # https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
  file-name-date-format: 'HH-mm-ss MM-dd-yyyy'

inventory-settings:
  # Set to 0 if you don't want the players to have any additional pages.
  # Number lower than 0 is not acceptable.
  # ATTENTION: This will also set to players' database if they don't have database before.
  max-page-default: 1
  # The default position of "PrevItem"
  # ATTENTION: This will also set to players' database if they don't have database before.
  prev-item-position-default: 18
  # The default position of "NextItem"
  # ATTENTION: This will also set to players' database if they don't have database before.
  next-item-position-default: 26
  # If "focus-using-default-item-position" is true, then the position of the items "PrevItem" and "NextItem" of all players will be set as the default setting.
  # Additionally, they cannot customize their own items "PrevItem" and "NextItem" position.
  focus-using-default-item-position: false
  # If "use-saved-current-page" is true, then when player join the server, it will show the page that they were in before.
  # For example, at the time they leave the server they're in page 5, so when they rejoin, it will automatically show page 5.
  # If it false, then it always shows the first page when player join.
  use-saved-current-page: true
  # If "keep-inventory" is true then whenever player die, their items will not drop.
  # If it is false, then the players will neeed these permissions below to keep their items when they die.
  # inventorypagesplus.keep.unopened - When the player dies, keep unopened pages, and drop items in the current opening page.
  # inventorypagesplus.keep.hotbar - When the player dies, Keep all items in the hotbar.
  # inventorypagesplus.keep.all - Keep all items when player die.
  keep-inventory: true
  # If this is enabled, plugin will show creative inventory database whenever player's mode changes to creative.
  # Otherwise, plugin will only use survival inventory database for all game modes.
  # PLEASE don't use reload command, please restart server after changing this option.
  use-creative-inventory: true

# Automatically move items to the next page if player's current page is full.
# However, Bukkit API does not let me execute the event when player's inventory is full.
# To fix this, player has to leave one slot empty in their page in order to allow the system to move items to the next page.
advanced-pick-up-settings:
  enabled: false
  action-bar:
    enabled: true
    text: '&f+%amount% %itemName%&r | Page: &e%page%&f | Slot: &e%slotNumber%'
  sound:
    enabled: true
    name: 'ENTITY_ITEM_PICKUP'
    volume: 1
    pitch: 1

# Using for collecting the number of players in the server.
# This option does not affect the server performance.
bStats:
  enabled: true