name: InventoryPagesPlus
version: '${project.version}'
main: me.cortezromeo.inventorypagesplus.InventoryPagesPlus
api-version: '1.13'
softdepend:
  - PlaceholderAPI
authors:
  - Cortez_Romeo
description: Add pages to inventories for expansive storage!
commands:
  inventorypagesplus:
    description: Main command
    aliases:
      - inventorypages
      - inventorypages+
      - inventoryp
      - tuidopage
      - tudopage
      - tuidopages
  clear:
    description: Clear inventory
    aliases:
      - clearinventory
      - ci
  setpageslot:
    description: Set pages' item slot
  invsee:
    description: See inventory of other players