name: InventoryPagesPlus
version: '${project.version}'
main: me.cortezromeo.inventorypagesplus.InventoryPagesPlus
api-version: '1.16'
softdepend:
  - PlaceholderAPI
authors:
  - Cortez_Romeo
description: Add pages to inventories for expansive storage!
commands:
  inventorypagesplus:
    description: Main command
    aliases:
      - inventorypages
      - inventorypage
      - inventorypages+
      - inventoryp
  clear:
    description: Clear current page
    aliases:
      - clearinventory
      - clearpage
      - clearcurrentpage
      - ci
  clearall:
    description: Clear all pages
    aliases:
      - clearallinventory
      - clearallpages
  setpageslot:
    description: Set pages' item slot
  invsee:
    description: See inventory of other players